#!/bin/sh

num=0;

read -p "Enter the file/directory name. : " name

if ["$name" == ""] 
then # no argument
	echo "No file/directory name was entered."
	exit 1;
elif [ ! -e "$name" ] # not exist
then
	echo "$name은 존재하지 않습니다."
	exit 1;
elif [ -e $name ] # find file type
then
	if [ -d $name ]
	then
		echo "$name은  디렉토리 파일입니다."	
	elif [ -b $name ]
	then	
		echo "$name은 블록장치 파일입니다."
	elif [ -c$name ]
        then
		echo "$name은 문자장치 파일입니다."
	elif [ -L $name ]
        then
		echo "$name은 심볼릭 링크 파일입니다."
	elif [ -p $name ]
        then
		echo "$name은 파이프 파일 입니다."
	elif [ -s $name ]
        then
		echo "$name은 소켓 파일입니다."
	elif [ -f $name ]
        then
		echo "$name은 일반 파일입니다."
	fi
	exit 0;
fi

